import frameForPortfolio from "../Assests/frame.png";

const dataForPortfolio = [
	{
		id: 1,
		heading: "Mi Portal U",
		figmaBtn: " Figma Community",
		frame: frameForPortfolio,
		btns: ["UX", "Uni", "JS"],
		// btnUX: "UX Design",
		// btnUni: "University",
		// btnJs: "JavaScript",
	},
	{
		id: 2,
		heading: "Mi Portal U",
		figmaBtn: "Figma Community",
		frame: frameForPortfolio,
		btns: ["UX", "Uni", "JS"],
		// btnUX: "UX Design",
		// btnUni: "University",
		// btnJs: "JavaScript",
	},
	{
		id: 3,
		heading: "Mi Portal U",
		figmaBtn: "Figma Community",
		frame: frameForPortfolio,

		// btns: ["UX", "Uni", "JS"],
		// btnUX: "UX Design",
		// btnUni: "University",
		// btnJs: "JavaScript",
	},
	{
		id: 4,
		heading: "Mi Portal U",
		figmaBtn: "Figma Commnunity",
		frame: frameForPortfolio,
		// btns: ["UX", "Uni", "JS"],
		// btnUX: "UX Design",
		// btnUni: "University",
		// btnJs: "JavaScript",
	},
	{
		id: 5,
		heading: "Mi Portal U",
		figmaBtn: "Figma Commnunity",
		frame: frameForPortfolio,
		// btns: ["UX", "Uni", "JS"],
	},
	{
		id: 6,
		heading: "Mi Portal U",
		figmaBtn: "Figma Commnunity",
		frame: frameForPortfolio,
		// btns: ["UX", "Uni", "JS"],
		// btnUX: "UX Design",
		// btnUni: "University",
		// btnJs: "JavaScript",
	},
	{
		id: 7,
		heading: "Mi Portal U",
		figmaBtn: "Figma Commnunity",
		frame: frameForPortfolio,
		// btnUX: "UX Design",
		// btnUni: "University",
		// btnJs: "JavaScript",
	},
	{
		id: 8,
		heading: "Mi Portal U",
		figmaBtn: "Figma Commnunity",
		frame: frameForPortfolio,
		// btns: ["UX", "Uni", "JS"],
		// btnUX: "UX Design",
		// btnUni: "University",
		// btnJs: "JavaScript",
	},
	{
		id: 9,
		heading: "Mi Portal U",
		figmaBtn: "Figma Commnunity",
		frame: frameForPortfolio,
		// btns: ["UX", "Uni", "JS"],
		// btnUX: "UX Design",
		// btnUni: "University",
		// btnJs: "JavaScript",
	},
];

export default dataForPortfolio;
